version: '3'
services:
  crawler:
    build: ./crawler/
    image: crawler:latest
    environment:
      - DEPLOY=docker
    expose:
      - "8101"
      - "8102"
      - "8104"
    ports:
      - 8101:8101
      - 8102:8102
      - 8104:8104
    depends_on:
      - redis
      - mongo
    networks:
      - main
  server:
    build: ./server/
    image: server:latest
    environment:
      - MONGO_HOST=mongo
    expose:
      - "3000"
    ports:
      - 80:3000
    depends_on:
      - mongo
    networks:
      - main
  redis:
    image: redis:alpine
    networks:
      - main
  mongo:
    image: mongo:3.6
    ports:
      # !!! development !!!
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      - main
volumes:
  mongodata:
networks:
  main:
    driver: bridge
