version: '3'
services:
  crawler:
    build: ./crawler/
    image: crawler:latest
    environment:
      - NODE_ENV=production
      - DEPLOY=docker
      - DEBUG=ws:*
    expose:
      - "8101"
      - "8102"
      - "8104"
    ports:
      - 8101:8101
      - 8102:8102
      - 8104:8104
    networks:
      - main
  bWechat:
    build: ./server/
    image: server:latest
    expose:
      - "3000"
    ports:
      - "80:3000"
    environment:
      - MONGO_HOST=mongo
    networks:
      - main
  redis:
    image: redis:alpine
    networks:
      - main
  mongo:
    image: mongo:3.6
    volumes:
      - mongodata:/data/db
    networks:
      - main
volumes:
  mongodata:
networks:
  main:
    driver: bridge
