version: '3'
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - /root/letsencrypt:/config
      # absolute path
    environment:
      - EMAIL=ritou11@gmail.com
      - URL=nogeek.top
      - SUBDOMAINS=wxpub
      - VALIDATION=http
      - TZ=China/Shanghai
      - PUID=0
      - PGID=0
  crawler:
    image: registry.cn-hangzhou.aliyuncs.com/wxpubanal/crawler:latest
    environment:
      - DEPLOY=docker
    expose:
      - "8101"
    ports:
      - 8101:8101
    depends_on:
      - redis
      - mongo
    networks:
      - main
  server:
    image: registry.cn-hangzhou.aliyuncs.com/wxpubanal/server:latest
    environment:
      - MONGO_HOST=mongo
    expose:
      - "3000"
    depends_on:
      - mongo
    networks:
      - main
  redis:
    image: redis:alpine
    networks:
      - main
  mongo:
    image: mongo:3.6
    volumes:
      - mongodata:/data/db
    networks:
      - main
volumes:
  mongodata:
networks:
  main:
    driver: bridge
