version: '3'
services:
  crawler:
    image: registry.cn-hangzhou.aliyuncs.com/wxpubvis/crawler:latest
    environment:
      - DEPLOY=docker
    expose:
      - "8101"
      - "8102"
      - "8104"
    ports:
      - 8101:8101
      - 8102:8102
      - 8104:8104
    volumes:
      - /root/myConfig.json:/app/myConfig.json
      #! absolute path
    depends_on:
      - redis
      - mongo
    networks:
      - main
  server:
    image: registry.cn-hangzhou.aliyuncs.com/wxpubvis/server:latest
    environment:
      - MONGO_HOST=mongo
      #! hardcoded
      - CORS_ORIGIN=http://192.10.10.108:3000
    expose:
      - "3000"
    ports:
      - 80:3000
    depends_on:
      - mongo
    networks:
      - main
  redis:
    image: redis:alpine
    networks:
      - main
  mongo:
    image: mongo:3.6
    ports:
      # !!! development !!!
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      - main
volumes:
  mongodata:
networks:
  main:
    driver: bridge
